#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria1.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SalesandInventorySystem")]
	public partial class ClsLinqSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertemployee(employee instance);
    partial void Updateemployee(employee instance);
    partial void Deleteemployee(employee instance);
    partial void Insertjob(job instance);
    partial void Updatejob(job instance);
    partial void Deletejob(job instance);
    partial void Insertlocation(location instance);
    partial void Updatelocation(location instance);
    partial void Deletelocation(location instance);
    partial void Insertmanager(manager instance);
    partial void Updatemanager(manager instance);
    partial void Deletemanager(manager instance);
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    partial void Insertsupplier(supplier instance);
    partial void Updatesupplier(supplier instance);
    partial void Deletesupplier(supplier instance);
    partial void Inserttbluser(tbluser instance);
    partial void Updatetbluser(tbluser instance);
    partial void Deletetbluser(tbluser instance);
    partial void Inserttype(type instance);
    partial void Updatetype(type instance);
    partial void Deletetype(type instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    partial void Insertorder_detail2(order_detail2 instance);
    partial void Updateorder_detail2(order_detail2 instance);
    partial void Deleteorder_detail2(order_detail2 instance);
    partial void Insertorder_detail(order_detail instance);
    partial void Updateorder_detail(order_detail instance);
    partial void Deleteorder_detail(order_detail instance);
    #endregion
		
		public ClsLinqSqlDataContext() : 
				base(global::Pizzaria1.Properties.Settings.Default.SalesandInventorySystemConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ClsLinqSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClsLinqSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClsLinqSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClsLinqSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
		
		public System.Data.Linq.Table<job> jobs
		{
			get
			{
				return this.GetTable<job>();
			}
		}
		
		public System.Data.Linq.Table<location> locations
		{
			get
			{
				return this.GetTable<location>();
			}
		}
		
		public System.Data.Linq.Table<manager> managers
		{
			get
			{
				return this.GetTable<manager>();
			}
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<supplier> suppliers
		{
			get
			{
				return this.GetTable<supplier>();
			}
		}
		
		public System.Data.Linq.Table<tbluser> tblusers
		{
			get
			{
				return this.GetTable<tbluser>();
			}
		}
		
		public System.Data.Linq.Table<type> types
		{
			get
			{
				return this.GetTable<type>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		public System.Data.Linq.Table<order_detail2> order_detail2s
		{
			get
			{
				return this.GetTable<order_detail2>();
			}
		}
		
		public System.Data.Linq.Table<order_detail> order_details
		{
			get
			{
				return this.GetTable<order_detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CATEGORY_ID;
		
		private string _NAME;
		
		private string _DESCRIPTION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCATEGORY_IDChanging(int value);
    partial void OnCATEGORY_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    #endregion
		
		public category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CATEGORY_ID
		{
			get
			{
				return this._CATEGORY_ID;
			}
			set
			{
				if ((this._CATEGORY_ID != value))
				{
					this.OnCATEGORY_IDChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_ID = value;
					this.SendPropertyChanged("CATEGORY_ID");
					this.OnCATEGORY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(100)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CUST_ID;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _PHONE_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUST_IDChanging(int value);
    partial void OnCUST_IDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnPHONE_NUMBERChanging(string value);
    partial void OnPHONE_NUMBERChanged();
    #endregion
		
		public customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this.OnCUST_IDChanging(value);
					this.SendPropertyChanging();
					this._CUST_ID = value;
					this.SendPropertyChanged("CUST_ID");
					this.OnCUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="NVarChar(20)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="NVarChar(20)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NUMBER", DbType="NVarChar(20)")]
		public string PHONE_NUMBER
		{
			get
			{
				return this._PHONE_NUMBER;
			}
			set
			{
				if ((this._PHONE_NUMBER != value))
				{
					this.OnPHONE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NUMBER = value;
					this.SendPropertyChanged("PHONE_NUMBER");
					this.OnPHONE_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employee")]
	public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMPLOYEE_ID;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _PHONE_NUMBER;
		
		private string _EMAIL;
		
		private System.Nullable<int> _JOB_ID;
		
		private System.Nullable<System.DateTime> _HIRED_DATE;
		
		private System.Nullable<int> _LOCATION_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMPLOYEE_IDChanging(int value);
    partial void OnEMPLOYEE_IDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnPHONE_NUMBERChanging(string value);
    partial void OnPHONE_NUMBERChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnJOB_IDChanging(System.Nullable<int> value);
    partial void OnJOB_IDChanged();
    partial void OnHIRED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnHIRED_DATEChanged();
    partial void OnLOCATION_IDChanging(System.Nullable<int> value);
    partial void OnLOCATION_IDChanged();
    #endregion
		
		public employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this.OnEMPLOYEE_IDChanging(value);
					this.SendPropertyChanging();
					this._EMPLOYEE_ID = value;
					this.SendPropertyChanged("EMPLOYEE_ID");
					this.OnEMPLOYEE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="NVarChar(20)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="NVarChar(20)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NUMBER", DbType="NVarChar(20)")]
		public string PHONE_NUMBER
		{
			get
			{
				return this._PHONE_NUMBER;
			}
			set
			{
				if ((this._PHONE_NUMBER != value))
				{
					this.OnPHONE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NUMBER = value;
					this.SendPropertyChanged("PHONE_NUMBER");
					this.OnPHONE_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_ID", DbType="Int")]
		public System.Nullable<int> JOB_ID
		{
			get
			{
				return this._JOB_ID;
			}
			set
			{
				if ((this._JOB_ID != value))
				{
					this.OnJOB_IDChanging(value);
					this.SendPropertyChanging();
					this._JOB_ID = value;
					this.SendPropertyChanged("JOB_ID");
					this.OnJOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRED_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> HIRED_DATE
		{
			get
			{
				return this._HIRED_DATE;
			}
			set
			{
				if ((this._HIRED_DATE != value))
				{
					this.OnHIRED_DATEChanging(value);
					this.SendPropertyChanging();
					this._HIRED_DATE = value;
					this.SendPropertyChanged("HIRED_DATE");
					this.OnHIRED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", DbType="Int")]
		public System.Nullable<int> LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.job")]
	public partial class job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JOB_ID;
		
		private string _JOB_TITLE;
		
		private System.Nullable<double> _SALARY;
		
		private string _Curence_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJOB_IDChanging(int value);
    partial void OnJOB_IDChanged();
    partial void OnJOB_TITLEChanging(string value);
    partial void OnJOB_TITLEChanged();
    partial void OnSALARYChanging(System.Nullable<double> value);
    partial void OnSALARYChanged();
    partial void OnCurence_TypeChanging(string value);
    partial void OnCurence_TypeChanged();
    #endregion
		
		public job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JOB_ID
		{
			get
			{
				return this._JOB_ID;
			}
			set
			{
				if ((this._JOB_ID != value))
				{
					this.OnJOB_IDChanging(value);
					this.SendPropertyChanging();
					this._JOB_ID = value;
					this.SendPropertyChanged("JOB_ID");
					this.OnJOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_TITLE", DbType="NChar(20)")]
		public string JOB_TITLE
		{
			get
			{
				return this._JOB_TITLE;
			}
			set
			{
				if ((this._JOB_TITLE != value))
				{
					this.OnJOB_TITLEChanging(value);
					this.SendPropertyChanging();
					this._JOB_TITLE = value;
					this.SendPropertyChanged("JOB_TITLE");
					this.OnJOB_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALARY", DbType="Float")]
		public System.Nullable<double> SALARY
		{
			get
			{
				return this._SALARY;
			}
			set
			{
				if ((this._SALARY != value))
				{
					this.OnSALARYChanging(value);
					this.SendPropertyChanging();
					this._SALARY = value;
					this.SendPropertyChanged("SALARY");
					this.OnSALARYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curence_Type", DbType="NChar(10)")]
		public string Curence_Type
		{
			get
			{
				return this._Curence_Type;
			}
			set
			{
				if ((this._Curence_Type != value))
				{
					this.OnCurence_TypeChanging(value);
					this.SendPropertyChanging();
					this._Curence_Type = value;
					this.SendPropertyChanged("Curence_Type");
					this.OnCurence_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.location")]
	public partial class location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LOCATION_ID;
		
		private string _CITY;
		
		private string _STREET;
		
		private string _PROVINCE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOCATION_IDChanging(int value);
    partial void OnLOCATION_IDChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTREETChanging(string value);
    partial void OnSTREETChanged();
    partial void OnPROVINCEChanging(string value);
    partial void OnPROVINCEChanged();
    #endregion
		
		public location()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(20)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREET", DbType="NVarChar(20)")]
		public string STREET
		{
			get
			{
				return this._STREET;
			}
			set
			{
				if ((this._STREET != value))
				{
					this.OnSTREETChanging(value);
					this.SendPropertyChanging();
					this._STREET = value;
					this.SendPropertyChanged("STREET");
					this.OnSTREETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCE", DbType="NVarChar(20)")]
		public string PROVINCE
		{
			get
			{
				return this._PROVINCE;
			}
			set
			{
				if ((this._PROVINCE != value))
				{
					this.OnPROVINCEChanging(value);
					this.SendPropertyChanging();
					this._PROVINCE = value;
					this.SendPropertyChanged("PROVINCE");
					this.OnPROVINCEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.manager")]
	public partial class manager : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANGER_ID;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private System.Nullable<int> _LOCATION_ID;
		
		private string _EMAIL;
		
		private string _PHONE_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANGER_IDChanging(int value);
    partial void OnMANGER_IDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnLOCATION_IDChanging(System.Nullable<int> value);
    partial void OnLOCATION_IDChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPHONE_NUMBERChanging(string value);
    partial void OnPHONE_NUMBERChanged();
    #endregion
		
		public manager()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANGER_ID
		{
			get
			{
				return this._MANGER_ID;
			}
			set
			{
				if ((this._MANGER_ID != value))
				{
					this.OnMANGER_IDChanging(value);
					this.SendPropertyChanging();
					this._MANGER_ID = value;
					this.SendPropertyChanged("MANGER_ID");
					this.OnMANGER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="NVarChar(20)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="NVarChar(20)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", DbType="Int")]
		public System.Nullable<int> LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(20)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NUMBER", DbType="NVarChar(20)")]
		public string PHONE_NUMBER
		{
			get
			{
				return this._PHONE_NUMBER;
			}
			set
			{
				if ((this._PHONE_NUMBER != value))
				{
					this.OnPHONE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NUMBER = value;
					this.SendPropertyChanged("PHONE_NUMBER");
					this.OnPHONE_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PRODUCT_ID;
		
		private string _NAME;
		
		private string _DESCRIPTION;
		
		private System.Nullable<int> _QTY_STOCK;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<int> _CATEGORY_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRODUCT_IDChanging(int value);
    partial void OnPRODUCT_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnQTY_STOCKChanging(System.Nullable<int> value);
    partial void OnQTY_STOCKChanged();
    partial void OnPRICEChanging(System.Nullable<double> value);
    partial void OnPRICEChanged();
    partial void OnCATEGORY_IDChanging(System.Nullable<int> value);
    partial void OnCATEGORY_IDChanged();
    #endregion
		
		public product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PRODUCT_ID
		{
			get
			{
				return this._PRODUCT_ID;
			}
			set
			{
				if ((this._PRODUCT_ID != value))
				{
					this.OnPRODUCT_IDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_ID = value;
					this.SendPropertyChanged("PRODUCT_ID");
					this.OnPRODUCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(20)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(100)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_STOCK", DbType="Int")]
		public System.Nullable<int> QTY_STOCK
		{
			get
			{
				return this._QTY_STOCK;
			}
			set
			{
				if ((this._QTY_STOCK != value))
				{
					this.OnQTY_STOCKChanging(value);
					this.SendPropertyChanging();
					this._QTY_STOCK = value;
					this.SendPropertyChanged("QTY_STOCK");
					this.OnQTY_STOCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_ID", DbType="Int")]
		public System.Nullable<int> CATEGORY_ID
		{
			get
			{
				return this._CATEGORY_ID;
			}
			set
			{
				if ((this._CATEGORY_ID != value))
				{
					this.OnCATEGORY_IDChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_ID = value;
					this.SendPropertyChanged("CATEGORY_ID");
					this.OnCATEGORY_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.supplier")]
	public partial class supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SUPPLIER_ID;
		
		private System.Nullable<int> _LOCATION_ID;
		
		private string _COMPANY_NAME;
		
		private string _PHONE_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSUPPLIER_IDChanging(int value);
    partial void OnSUPPLIER_IDChanged();
    partial void OnLOCATION_IDChanging(System.Nullable<int> value);
    partial void OnLOCATION_IDChanged();
    partial void OnCOMPANY_NAMEChanging(string value);
    partial void OnCOMPANY_NAMEChanged();
    partial void OnPHONE_NUMBERChanging(string value);
    partial void OnPHONE_NUMBERChanged();
    #endregion
		
		public supplier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SUPPLIER_ID
		{
			get
			{
				return this._SUPPLIER_ID;
			}
			set
			{
				if ((this._SUPPLIER_ID != value))
				{
					this.OnSUPPLIER_IDChanging(value);
					this.SendPropertyChanging();
					this._SUPPLIER_ID = value;
					this.SendPropertyChanged("SUPPLIER_ID");
					this.OnSUPPLIER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", DbType="Int")]
		public System.Nullable<int> LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="NVarChar(20)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this.OnCOMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_NAME = value;
					this.SendPropertyChanged("COMPANY_NAME");
					this.OnCOMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NUMBER", DbType="NVarChar(20)")]
		public string PHONE_NUMBER
		{
			get
			{
				return this._PHONE_NUMBER;
			}
			set
			{
				if ((this._PHONE_NUMBER != value))
				{
					this.OnPHONE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NUMBER = value;
					this.SendPropertyChanged("PHONE_NUMBER");
					this.OnPHONE_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbluser")]
	public partial class tbluser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _USERNAME;
		
		private System.Nullable<int> _TYPE_ID;
		
		private string _PASSWORD;
		
		private System.Nullable<int> _LOCATION_ID;
		
		private string _PHONE_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnTYPE_IDChanging(System.Nullable<int> value);
    partial void OnTYPE_IDChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnLOCATION_IDChanging(System.Nullable<int> value);
    partial void OnLOCATION_IDChanged();
    partial void OnPHONE_NUMBERChanging(string value);
    partial void OnPHONE_NUMBERChanged();
    #endregion
		
		public tbluser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="NVarChar(20)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="NVarChar(20)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_ID", DbType="Int")]
		public System.Nullable<int> TYPE_ID
		{
			get
			{
				return this._TYPE_ID;
			}
			set
			{
				if ((this._TYPE_ID != value))
				{
					this.OnTYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._TYPE_ID = value;
					this.SendPropertyChanged("TYPE_ID");
					this.OnTYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_ID", DbType="Int")]
		public System.Nullable<int> LOCATION_ID
		{
			get
			{
				return this._LOCATION_ID;
			}
			set
			{
				if ((this._LOCATION_ID != value))
				{
					this.OnLOCATION_IDChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_ID = value;
					this.SendPropertyChanged("LOCATION_ID");
					this.OnLOCATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NUMBER", DbType="NVarChar(20)")]
		public string PHONE_NUMBER
		{
			get
			{
				return this._PHONE_NUMBER;
			}
			set
			{
				if ((this._PHONE_NUMBER != value))
				{
					this.OnPHONE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NUMBER = value;
					this.SendPropertyChanged("PHONE_NUMBER");
					this.OnPHONE_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.type")]
	public partial class type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TYPE_ID;
		
		private string _TYPE1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTYPE_IDChanging(int value);
    partial void OnTYPE_IDChanged();
    partial void OnTYPE1Changing(string value);
    partial void OnTYPE1Changed();
    #endregion
		
		public type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TYPE_ID
		{
			get
			{
				return this._TYPE_ID;
			}
			set
			{
				if ((this._TYPE_ID != value))
				{
					this.OnTYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._TYPE_ID = value;
					this.SendPropertyChanged("TYPE_ID");
					this.OnTYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TYPE", Storage="_TYPE1", DbType="NVarChar(50)")]
		public string TYPE1
		{
			get
			{
				return this._TYPE1;
			}
			set
			{
				if ((this._TYPE1 != value))
				{
					this.OnTYPE1Changing(value);
					this.SendPropertyChanging();
					this._TYPE1 = value;
					this.SendPropertyChanged("TYPE1");
					this.OnTYPE1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[order]")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ORDER_ID;
		
		private System.Nullable<int> _CUST_ID;
		
		private string _DESCRIBTUON_ORDER;
		
		private System.Nullable<System.DateTime> _DATE_ORDER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnORDER_IDChanging(int value);
    partial void OnORDER_IDChanged();
    partial void OnCUST_IDChanging(System.Nullable<int> value);
    partial void OnCUST_IDChanged();
    partial void OnDESCRIBTUON_ORDERChanging(string value);
    partial void OnDESCRIBTUON_ORDERChanged();
    partial void OnDATE_ORDERChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_ORDERChanged();
    #endregion
		
		public order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ORDER_ID
		{
			get
			{
				return this._ORDER_ID;
			}
			set
			{
				if ((this._ORDER_ID != value))
				{
					this.OnORDER_IDChanging(value);
					this.SendPropertyChanging();
					this._ORDER_ID = value;
					this.SendPropertyChanged("ORDER_ID");
					this.OnORDER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", DbType="Int")]
		public System.Nullable<int> CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this.OnCUST_IDChanging(value);
					this.SendPropertyChanging();
					this._CUST_ID = value;
					this.SendPropertyChanged("CUST_ID");
					this.OnCUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIBTUON_ORDER", DbType="NVarChar(105)")]
		public string DESCRIBTUON_ORDER
		{
			get
			{
				return this._DESCRIBTUON_ORDER;
			}
			set
			{
				if ((this._DESCRIBTUON_ORDER != value))
				{
					this.OnDESCRIBTUON_ORDERChanging(value);
					this.SendPropertyChanging();
					this._DESCRIBTUON_ORDER = value;
					this.SendPropertyChanged("DESCRIBTUON_ORDER");
					this.OnDESCRIBTUON_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_ORDER", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_ORDER
		{
			get
			{
				return this._DATE_ORDER;
			}
			set
			{
				if ((this._DATE_ORDER != value))
				{
					this.OnDATE_ORDERChanging(value);
					this.SendPropertyChanging();
					this._DATE_ORDER = value;
					this.SendPropertyChanged("DATE_ORDER");
					this.OnDATE_ORDERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_details")]
	public partial class order_detail2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ORDER_details;
		
		private System.Nullable<int> _ID_PRODUCT;
		
		private System.Nullable<int> _ID_ORDER;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<double> _DISCOUNT;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<double> _AMOUNT;
		
		private System.Nullable<double> _TOTAL_AMOUNT;
		
		private string _Property1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ORDER_detailsChanging(int value);
    partial void OnID_ORDER_detailsChanged();
    partial void OnID_PRODUCTChanging(System.Nullable<int> value);
    partial void OnID_PRODUCTChanged();
    partial void OnID_ORDERChanging(System.Nullable<int> value);
    partial void OnID_ORDERChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnDISCOUNTChanging(System.Nullable<double> value);
    partial void OnDISCOUNTChanged();
    partial void OnPRICEChanging(System.Nullable<double> value);
    partial void OnPRICEChanged();
    partial void OnAMOUNTChanging(System.Nullable<double> value);
    partial void OnAMOUNTChanged();
    partial void OnTOTAL_AMOUNTChanging(System.Nullable<double> value);
    partial void OnTOTAL_AMOUNTChanged();
    partial void OnProperty1Changing(string value);
    partial void OnProperty1Changed();
    #endregion
		
		public order_detail2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER_details", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ORDER_details
		{
			get
			{
				return this._ID_ORDER_details;
			}
			set
			{
				if ((this._ID_ORDER_details != value))
				{
					this.OnID_ORDER_detailsChanging(value);
					this.SendPropertyChanging();
					this._ID_ORDER_details = value;
					this.SendPropertyChanged("ID_ORDER_details");
					this.OnID_ORDER_detailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCT", DbType="Int")]
		public System.Nullable<int> ID_PRODUCT
		{
			get
			{
				return this._ID_PRODUCT;
			}
			set
			{
				if ((this._ID_PRODUCT != value))
				{
					this.OnID_PRODUCTChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCT = value;
					this.SendPropertyChanged("ID_PRODUCT");
					this.OnID_PRODUCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this.OnID_ORDERChanging(value);
					this.SendPropertyChanging();
					this._ID_ORDER = value;
					this.SendPropertyChanged("ID_ORDER");
					this.OnID_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="Float")]
		public System.Nullable<double> DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this.OnDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNT = value;
					this.SendPropertyChanged("DISCOUNT");
					this.OnDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Float")]
		public System.Nullable<double> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this.OnAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT = value;
					this.SendPropertyChanged("AMOUNT");
					this.OnAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Float")]
		public System.Nullable<double> TOTAL_AMOUNT
		{
			get
			{
				return this._TOTAL_AMOUNT;
			}
			set
			{
				if ((this._TOTAL_AMOUNT != value))
				{
					this.OnTOTAL_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_AMOUNT = value;
					this.SendPropertyChanged("TOTAL_AMOUNT");
					this.OnTOTAL_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property1", CanBeNull=false)]
		public string Property1
		{
			get
			{
				return this._Property1;
			}
			set
			{
				if ((this._Property1 != value))
				{
					this.OnProperty1Changing(value);
					this.SendPropertyChanging();
					this._Property1 = value;
					this.SendPropertyChanged("Property1");
					this.OnProperty1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_details")]
	public partial class order_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ORDER_details;
		
		private System.Nullable<int> _ID_PRODUCT;
		
		private System.Nullable<int> _ID_ORDER;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<double> _DISCOUNT;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<double> _AMOUNT;
		
		private System.Nullable<double> _TOTAL_AMOUNT;
		
		private System.Nullable<bool> _TYPE_ORDER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ORDER_detailsChanging(int value);
    partial void OnID_ORDER_detailsChanged();
    partial void OnID_PRODUCTChanging(System.Nullable<int> value);
    partial void OnID_PRODUCTChanged();
    partial void OnID_ORDERChanging(System.Nullable<int> value);
    partial void OnID_ORDERChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnDISCOUNTChanging(System.Nullable<double> value);
    partial void OnDISCOUNTChanged();
    partial void OnPRICEChanging(System.Nullable<double> value);
    partial void OnPRICEChanged();
    partial void OnAMOUNTChanging(System.Nullable<double> value);
    partial void OnAMOUNTChanged();
    partial void OnTOTAL_AMOUNTChanging(System.Nullable<double> value);
    partial void OnTOTAL_AMOUNTChanged();
    partial void OnTYPE_ORDERChanging(System.Nullable<bool> value);
    partial void OnTYPE_ORDERChanged();
    #endregion
		
		public order_detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER_details", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ORDER_details
		{
			get
			{
				return this._ID_ORDER_details;
			}
			set
			{
				if ((this._ID_ORDER_details != value))
				{
					this.OnID_ORDER_detailsChanging(value);
					this.SendPropertyChanging();
					this._ID_ORDER_details = value;
					this.SendPropertyChanged("ID_ORDER_details");
					this.OnID_ORDER_detailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCT", DbType="Int")]
		public System.Nullable<int> ID_PRODUCT
		{
			get
			{
				return this._ID_PRODUCT;
			}
			set
			{
				if ((this._ID_PRODUCT != value))
				{
					this.OnID_PRODUCTChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCT = value;
					this.SendPropertyChanged("ID_PRODUCT");
					this.OnID_PRODUCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this.OnID_ORDERChanging(value);
					this.SendPropertyChanging();
					this._ID_ORDER = value;
					this.SendPropertyChanged("ID_ORDER");
					this.OnID_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="Float")]
		public System.Nullable<double> DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this.OnDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNT = value;
					this.SendPropertyChanged("DISCOUNT");
					this.OnDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Float")]
		public System.Nullable<double> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this.OnAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT = value;
					this.SendPropertyChanged("AMOUNT");
					this.OnAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Float")]
		public System.Nullable<double> TOTAL_AMOUNT
		{
			get
			{
				return this._TOTAL_AMOUNT;
			}
			set
			{
				if ((this._TOTAL_AMOUNT != value))
				{
					this.OnTOTAL_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_AMOUNT = value;
					this.SendPropertyChanged("TOTAL_AMOUNT");
					this.OnTOTAL_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_ORDER", DbType="Bit")]
		public System.Nullable<bool> TYPE_ORDER
		{
			get
			{
				return this._TYPE_ORDER;
			}
			set
			{
				if ((this._TYPE_ORDER != value))
				{
					this.OnTYPE_ORDERChanging(value);
					this.SendPropertyChanging();
					this._TYPE_ORDER = value;
					this.SendPropertyChanged("TYPE_ORDER");
					this.OnTYPE_ORDERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
